### ISSUE TITLE
[d2mapapi_mod v1.2.0] Diablo II Legacy: Failed to load DLLs! 

### ISSUE THREAD

**Issue by zeromovie** [soarqin/D2RMH#100]

**Comment by soarqin** [comment]
1. Please note D2RMH only support certain versions of D2 legacy client, ensure you are running it on corret version of D2 legacy.
2. Please check `d2_path` in D2RMH.ini if you are not running from D2 legacy client folder
3. Please check if `d2mapapi_piped.exe` is available, it might be killed by anti-virus software.

**Comment by zeromovie** [comment]
> 1. Please note that D2RMH only supports certain versions of D2 legacy client. Ensure that you are running it on corret version of D2 legacy.
> 2. Please check `d2_path` in D2RMH.ini if you are not running from D2 legacy client folder.
> 3. Please check if `d2mapapi_piped.exe` is available, it might be killed by anti-virus software.

Thanks, the reason is I forget to download d21.13c game
