### ISSUE TITLE
今天游戏客户端升级了一个小补丁，开图就无法使用了

### ISSUE THREAD

**Issue by bigmahou** [soarqin/D2RMH#105]
昨天使用还是一切正常，今天客户端更新了以后就无法使用了
尝试从新解压一份出来，中文或英文版，都不行

**Comment by tianqisor** [comment]
是啊 贼难受  大佬最近没时间吗

**Comment by lljyy227** [comment]
看来大佬最近没空了，天梯没有图，难受啊

**Comment by lljyy227** [comment]
> 是啊 贼难受 大佬最近没时间吗

去用这个吧，MapAssist，我现在用着没问题
https://mapassist.github.io/

**Comment by lljyy227** [comment]
> 去用这个吧，MapAssist，我现在用着没问题
> https://mapassist.github.io/

**Comment by soarqin** [comment]
已更新，因为工作原因不能保证及时更新，因此如果用MapAssist的话建议就继续用吧
