### ISSUE TITLE
Latest always crashes in Act5

### ISSUE THREAD

**Issue by CrazyPotatoes** [soarqin/D2RMH#11]
The release .04 sometimes crashed in act 2, but the latest files compiled crash >90% of the time when entering act 5. Sorry I couldn't figure it out

**Comment by soarqin** [comment]
met crash once in ACT2
Since I have rewritten the whole rendering system, need more test to see if the crash is fixed

**Comment by CrazyPotatoes** [comment]
No, I haven't seen any crashing yet.

**Comment by soarqin** [comment]
ok, so close first.
you can reopen it if crashes come again.
