### ISSUE TITLE
Release v0.4 not working after d2r client update 1.0.66878

### ISSUE THREAD

**Issue by drgyn** [soarqin/D2RMH#13]
As title says myself and some others i know do not see the map overlay in game anymore after today client patch.

**Comment by ModernAesthetics** [comment]
This needs to be updated (new offset):
uint64_t playerPtr = baseAddr_ + 0x20546E0;

**Comment by drgyn** [comment]
Thanks that appears correct when comparing to another map program that updated today will try and compile one myself

**Comment by brahnan** [comment]
Can you give a compiled program?

**Comment by s1228** [comment]
yeah, would also appreciate a new pre-build release. I cant get this to build properly :(

**Comment by soarqin** [comment]
next major version will be released with limited monsters/shrines display
and I am off my PC so that cannot upload precompiled binary here
so I uploaded it to gofile [here](https://gofile.io/d/wWlNZ0)

**Comment by s1228** [comment]
I just get:   This file does not exist.

**Comment by drgyn** [comment]
Thanks we appreciate it looks like we were able to compile a version as well cant wait for the new one.

**Comment by s1228** [comment]
I got it to compile as well, but doesnt seem to work. neither with the current offsets in the repo nor with the ones posted above. guess ill just wait for a proper release :)

**Comment by soarqin** [comment]
> I just get:   This file does not exist.
> 

sry for mistake, updated link

**Comment by s1228** [comment]
> > I just get:   This file does not exist.
> 
> sry for mistake, updated link

unfortunately still not working :( "403 - forbidden" this time

**Comment by CrazyPotatoes** [comment]
you also need this offset 
mapEnablePtr_ = baseAddr_ + 0x20643A2;

**Comment by ModernAesthetics** [comment]
I was able to compile and it is working but only works when I put it in the DII 1.13 folder (not d2r)
Path does not seem to work from ini for me.

**Comment by brahnan** [comment]
> 我能够编译并且它正在工作，但只有当我把它放在 DII 1.13 文件夹（不是 d2r） 中时才有效Path 似乎对我来说从 ini 不起作用。

Me too.

**Comment by soarqin** [comment]
v0.5 released, should be working now
