### ISSUE TITLE
Failed to loading DLLs!

### ISSUE THREAD

**Issue by ModernAesthetics** [soarqin/D2RMH#14]
compiled with new offset for latest patch but when I tried to run I get:
Diablo II Legacy v1.13c: Failed to loading DLLs!

Side note: Maybe fix verbage to "Failed to load DLLs!"

**Comment by soarqin** [comment]
check d2path in D2RMH.ini, or put exe in d2 1.13c folder with unmodified ini

**Comment by ModernAesthetics** [comment]
ini path not working but does work in the 1.13c folder

**Comment by soarqin** [comment]
fixed in v0.5
