### ISSUE TITLE
Display on bigger resolution

### ISSUE THREAD

**Issue by HOURS1212** [soarqin/D2RMH#19]
using 2560×1440  and multiple monitor, the overlay goes to the other monitors.

using x1080 shows correctly.

**Comment by HOURS1212** [comment]
using 0.5.1

**Comment by HOURS1212** [comment]
Using 0.5.3 map overlay on left or center fixes the issue.

Still broken if on right side.

**Comment by soarqin** [comment]
fixed a window position bug while set `postion=1` in v0.6, you can check if this resolved your problem

**Comment by HOURS1212** [comment]
Fixed.
