### ISSUE TITLE
Compilation problem or error report I don’t know where the problem is, please guide

### ISSUE THREAD

**Issue by jxsr099** [soarqin/D2RMH#20]
![image](https://user-images.githubusercontent.com/18099423/140629132-d5f154e1-a8dc-40ad-88ac-e321930a8c29.png)

**Comment by jxsr099** [comment]
![image](https://user-images.githubusercontent.com/18099423/140629777-2b003aac-cb91-40f6-81cc-343b14b80fec.png)

**Comment by jxsr099** [comment]
Code compilation error

**Comment by soarqin** [comment]
please update your mingw. suggest using mingw32 from MSYS2

**Comment by arithxp** [comment]
why not used released file?

**Comment by PMySQLQ** [comment]
I like to compile by myself so I can learn
