### ISSUE TITLE
Visual Studio Code Can't build?

### ISSUE THREAD

**Issue by PMySQLQ** [soarqin/D2RMH#21]
![image](https://user-images.githubusercontent.com/86890440/140642343-e7fa43a3-9484-4c99-b6cf-7f6592f4b0e2.png)

**Comment by soarqin** [comment]
check your toolchain, you should use C++ compiler either from Win10SDK/Visual Studio 2019 or 32bit MinGW 5.0+ with GCC 9.0+(suggest using MSYS2 to install)

**Comment by soarqin** [comment]
close due to no further response
