### ISSUE TITLE
Brother, can you come up with a Visual Studio 2019 + CMAKE build video tutorial

### ISSUE THREAD

**Issue by PMySQLQ** [soarqin/D2RMH#22]
Brother, can you come up with a Visual Studio 2019 + CMAKE build video tutorial

**Comment by arithxp** [comment]
just google it
https://www.youtube.com/watch?v=LxHV-KNEG3k
3:45 set option with win32

**Comment by PMySQLQ** [comment]
Is it you in the video?

**Comment by arithxp** [comment]
> 
> 
> Is it you in the video?

no. This is a video I found through a Google search.
It's a 2017 video, but it's still the same.

**Comment by PMySQLQ** [comment]
You can make a compiled video for me

**Comment by arithxp** [comment]
> 
> 
> You can make a compiled video for me

just watch the video and do it
or
read this https://github.com/soarqin/D2RMH#microsoft-visual-studio-2019

Watch the video and follow along, or follow the instruction manual, but in the end, it's the same.

**Comment by PMySQLQ** [comment]
It didn't work. I tested it many times

**Comment by PMySQLQ** [comment]
![image](https://user-images.githubusercontent.com/86890440/140646217-1db375dc-9a3b-45e1-afeb-10312e2546b9.png)

**Comment by arithxp** [comment]
cmake-gui run with administrator privilege.

**Comment by PMySQLQ** [comment]
![image](https://user-images.githubusercontent.com/86890440/140647262-44bbbdb3-f335-4b58-b854-03e60f69a79d.png)

**Comment by PMySQLQ** [comment]
![image](https://user-images.githubusercontent.com/86890440/140647523-270f4fed-4500-44b5-8a62-322232694604.png)

**Comment by PMySQLQ** [comment]
![image](https://user-images.githubusercontent.com/86890440/140647543-ac3ade31-bb6e-4fbf-b53e-d2526fb3981b.png)

**Comment by arithxp** [comment]
I'm using Visual Studio 2019 Community Edition.
If you set the platform to win32 in cmake-gui and generate it, it works 100%.

Don't forget to switch to release when building.

**Comment by PMySQLQ** [comment]
I have succeeded, thank you

**Comment by arithxp** [comment]
> 
> 
> I have succeeded, thank you

Good
