### ISSUE TITLE
Too much enchant information

### ISSUE THREAD

**Issue by mgmcmk** [soarqin/D2RMH#24]
When 3 or more enchantments are displayed, it is difficult to distinguish them.
Also, depending on the job, certain enchantments do not require marking.
ex) Hammer Paladin can be ignored except for the Magic Immune.
Therefore, it would be nice if only specific enchantments or immuns could be displayed.

If possible, it would be nice if the user could change the name arbitrarily.
(It will be easier to recognize if you set it to the native language rather than the alphabetic characters.)

**Comment by soarqin** [comment]
currently I just follow the rule of d2hackmap but yet add their switches to config, will be added soon

**Comment by soarqin** [comment]
as of v0.5.3, all enchant strings can be set in config now
