### ISSUE TITLE
cannot create and join rooms after running

### ISSUE THREAD

**Issue by wk4work** [soarqin/D2RMH#27]
Cannot create and join rooms after running
Return to normal after closing

**Comment by soarqin** [comment]
Try create room first then run this program

**Comment by wk4work** [comment]
> Try create room first then run this program

Does not necessarily happen
I will study the specific situation to see if it is a network problem

**Comment by soarqin** [comment]
close first
you are welcome to repoen it if you find the way to reproduce the bug
