### ISSUE TITLE
Suggestion: Option to toggle on all monsters on map.

### ISSUE THREAD

**Issue by Jarboy87** [soarqin/D2RMH#28]
This would be particularly useful for Cows.
Even if you just add a config line we can edit, would be great.
I notice that Elites already show as red dots.

**Comment by soarqin** [comment]
this is planned, but it might impact performance when there are too many near by monsters

**Comment by Jarboy87** [comment]
I recompiled the latest commit because I saw you added show normal monsters. Works well, I can't notice any performance issues but I'm running an 8th Gen i7 with 32GB Ram, but doesn't seem to resource hog even during heavy maps.

**Comment by PMySQLQ** [comment]
Can open monster health bar

**Comment by soarqin** [comment]
@PMySQLQ  no space to show health bar
