### ISSUE TITLE
D2 1.13c Install Location - Auto Find

### ISSUE THREAD

**Issue by derekShaheen** [soarqin/D2RMH#29]
Hello, I have a possible suggestion regarding the Diablo II installation files.

Perhaps the program could check, given the default setting for the d2_path being ".", if this is the default value, to evaluate the local folder, otherwise if it does not detect the files, it could query the registry location for the installation and attempt to use that path?

Check out the following registry location: HKCU\SOFTWARE\Blizzard Entertainment\Diablo II
Located here is an "InstallPath", which contains the path to the most recent installation of Diablo II.

**Comment by Jarboy87** [comment]
I would assume that 99% of people using this won't have that registry key because they don't have Diablo II installed.
The only thing required for this is the minimal files (link included on the main git).
The easiest way to manage this is to put the D2RMH files within the Diablo 2 minimal files folder, then it does auto detect within the local folder.

Otherwise, edit the INI.

**Comment by derekShaheen** [comment]
Perhaps, but I would hesitate to put a number against how many people have the install or not. I personally used the Blizzard installers found for free on their download repository. It doesn't take much to check if a registry key exists, just to handle the scenario for the set of users who have the install.
Example links to blizzard downloads.. 
d2 - https://www.blizzard.com/download/confirmation?platform=windows&locale=en_US&product=d2
d2lod - https://www.blizzard.com/download/confirmation?platform=windows&locale=en_US&product=d2lod
d2 1.13c patch - http://ftp.blizzard.com/pub/diablo2exp/patches/PC/LODPatch_113c.exe

**Comment by soarqin** [comment]
I think most ppl with d2legacy installations should be on 1.14d and it is hard to downgrade without a clean reinstallation. But reading from registry is not a bad idea, I will add it as fallback path later

**Comment by soarqin** [comment]
@derekShaheen one thing more, official d2legacy downloader downloads 1.14(a or b) now, cannot use 1.13c updater to do update, ppl have to find older installer themselves.

**Comment by soarqin** [comment]
implemented in v0.6, since the official installer is d2legacy v1.14+ now, I have not added the official legacy client installation instruction to README.
