### ISSUE TITLE
Suggestion: High rune drop notification

### ISSUE THREAD

**Issue by Jarboy87** [soarqin/D2RMH#30]
I know this is probably last on the list of things.

But it would be a nice addition to include some loot drop features.

**Comment by soarqin** [comment]
think this is possible, but I need to test the differences in new ItemData struct, like what did to StatList(find aura type) and MonsterData(find monster enchants)

**Comment by cakarlen** [comment]
This would be fantastic to add!

**Comment by mike-code** [comment]
I'd just be flattered to have this feature. Woinder if this struct would also include ilvl apart from item id and rarity type

**Comment by soarqin** [comment]
> I'd just be flattered to have this feature. Woinder if this struct would also include ilvl apart from item id and rarity type

quality and ilvl are in struct, and ethereal/sockets are detected as well, similar to d2hackmap
you can check item_support branch for progress

**Comment by mike-code** [comment]
looks like it's time for some GH sponsors sign up:)

**Comment by soarqin** [comment]
found ilvl field is always 1 in memory, think blizzard hide it in D2R

**Comment by soarqin** [comment]
the item filter function is on the master branch now, will be released as v0.6 after enought tests taken.
read comments in `D2RMH_item.ini` before set your own item filter rules.
will close this after v0.6 is released.
PS: ilvl is still not found in current memory region.

**Comment by soarqin** [comment]
close this, fire new issues if there is anything wrong in the item filter system
