### ISSUE TITLE
Occassionally Selects Wrong Player

### ISSUE THREAD

**Issue by derekShaheen** [soarqin/D2RMH#31]
Sometimes seems to select wrong player to display.

![image](https://user-images.githubusercontent.com/38998433/141272271-61d21d54-4aaa-4b50-bcae-1c39773f6c3d.png)

**Comment by soarqin** [comment]
this is a known bug and currently there is no approach to detect which Unit(PlayerData) is controlled by yourself
so in multiplayer game it will select a random player when there are more than one in this map level(area)

**Comment by Jarboy87** [comment]
For now let players specify the player name within D2RMH.INI if this is a suitable workaround for multiplayer.

**Comment by derekShaheen** [comment]
> 
> 
> For now let players specify the player name within D2RMH.INI if this is a suitable workaround for multiplayer. (if this is possible with what can currently be read)

Personally I'm switching characters so often, I'm not sure this would be very effective - at least for me. It would be interesting to see all of the players on the map though. Then it would only be a matter of a different character being highlighted temporarily.

**Comment by Jarboy87** [comment]
> > For now let players specify the player name within D2RMH.INI if this is a suitable workaround for multiplayer. (if this is possible with what can currently be read)
> 
> Personally I'm switching characters so often, I'm not sure this would be very effective - at least for me. It would be interesting to see all of the players on the map though. Then it would only be a matter of a different character being highlighted temporarily.

I know its not ideal, but if theres no way to differentiate which Unit is controlled by you in multiplayer games, but player names are available in PlayerData or some other means, it's probably the best workaround at this stage. You could list all your character names in the config, separated by commas, assigned to strings or an array etc.

Im only saying all this because I'm wanting to use this in Multiplayer games, and its currently an issue for me as well.

**Comment by soarqin** [comment]
think can add a hotkey to switch between players

**Comment by derekShaheen** [comment]
Hello @soarqin, love the change so we can see all players now. Thank you for that. One suggestion for you is offset 0x70 from the player unit should be the pointer to the inventory. I believe this offset returns 0x00 when checked against a non-local player. If it returns a value, then you've selected the current local player.

**Comment by soarqin** [comment]
actually inventoryPtr is player unit offset 0x90(see https://github.com/soarqin/D2RMH/blob/master/src/d2rdefs.h#L598), and it is not 0x00 for all players.
I have found a new way to check for current player, which is the offset 0x10 in PlayerData, right after the player's name, this value is always 0 for local player and non-zero for other players.
