### ISSUE TITLE
some issue on build code

### ISSUE THREAD

**Issue by px4860** [soarqin/D2RMH#37]
i got some trouble on build the code when i run **make -Cbuild**
![无标题](https://user-images.githubusercontent.com/49635060/141674739-0b6f7afd-716c-45b9-aabd-7703dab16332.png)

**Comment by soarqin** [comment]
1. if using MSYS2, update your gcc and mingw to latest by typing `pacman -Syu --noconfirm`
2. if using MSYS from official MinGW, try to get latest precompiled mingw-w64 package (from sourceforge downloads). if you don't know how to do this, just do MSYS2 fresh installation following instructions in README

**Comment by px4860** [comment]
> 1. if using MSYS2, update your gcc and mingw to latest by typing `pacman -Syu --noconfirm`
> 2. if using MSYS from official MinGW, try to get latest precompiled mingw-w64 package (from sourceforge downloads). if you don't know how to do this, just do MSYS2 fresh installation following instructions in README

i have updated my gcc and mingw and its show that is up to date and it still can't build.
there is some information.
![WJZU~D{65IJA_42RUZ RSUU](https://user-images.githubusercontent.com/49635060/141711882-525c4b47-7a17-4f49-a64e-272448be8f65.png)
![%X7I{O92NM_5 7D4JIS0 ~K](https://user-images.githubusercontent.com/49635060/141711963-0ab26e00-5e10-4369-b129-afb93e472c75.png)
![F%X PL6~27LKD~J~X5`E%`9](https://user-images.githubusercontent.com/49635060/141711999-2497b93a-fdf9-4d06-a70a-6ddcb643bdfd.png)
![5A8Z QM@B1E9 ~7%$T%J(0](https://user-images.githubusercontent.com/49635060/141712263-3a241a54-3765-4273-a935-a302abab86d0.png)

**Comment by soarqin** [comment]
Start a MinGW32 window (using mingw32.exe), not a MSYS window(using msys2.exe)
Please note that each .exe sets differecnt dev environment, MSYS2.exe is only for MSYS2 shell program development

**Comment by soarqin** [comment]
seems like you are using gcc not g++ to do th link, don't know what is wrong
you can try to:
1. confirm you have g++ from mingw(`which g++` returns `/mingw32/bin/g++`)
2. completely remove build folder and try it again
3. if still not working, try remove MSYS2's own gcc first(`pacman -Rcns gcc`) and redo step 2

**Comment by soarqin** [comment]
tested by installing a clean MSYS2, found the thing is that something wrong in instruction:
you should install `mingw-w64-i686-cmake` not `cmake`, I have fixed it in README, sorry for my mistake.

**Comment by px4860** [comment]
it works, thx :)
