### ISSUE TITLE
Not working for Multi-Instance 打开多个D2R窗口时，地图不起作用

### ISSUE THREAD

**Issue by SuniceMoMo** [soarqin/D2RMH#38]

**Comment by soarqin** [comment]
已知bug，暂时不会解决(通常来说单机多开只需要一张地图就够了)

**Comment by soarqin** [comment]
Tested on D2RML, to make it working for one of the window, run D2RMH.exe as Administor pls.
在D2RML上测试了下，要让其中一个窗口显示地图，需要用管理员运行身份运行D2RMH.exe
