### ISSUE TITLE
When editing an enchantment word, the letters are broken.

### ISSUE THREAD

**Issue by arithxp** [soarqin/D2RMH#43]
I set only the mob's immun and changed it to a nice looking word, but the letters are broken or only the first two letters are displayed.

![image](https://user-images.githubusercontent.com/6009737/142134023-28d36bbb-ed77-46fd-bbea-d04b7510f8ca.png)
English: Display only two letters

![image](https://user-images.githubusercontent.com/6009737/142134892-b274e2ac-2260-4173-9a63-e409650a25c7.png)

non English: Characters are broken

**Comment by soarqin** [comment]
words are trimmed to 3 characters(including the color indicator), think 2 chars are enough for indicating different enchants(as what d2hackmap did)
thus I can use string with static-length to save memory and cpu usage, due to low efficiency of dynamic string concatenation in C++

**Comment by arithxp** [comment]
I think it's already saved as utf-8 without BOM.
The font is Microsoft's official font used from Windows Vista and I know that it supports charset. 
(font name is 'malgun gothic' file name malgun.ttf)

gulim font
![image](https://user-images.githubusercontent.com/6009737/142138449-382877c0-b8ec-4cce-8693-47f33577e684.png)

malgun gothic font
![image](https://user-images.githubusercontent.com/6009737/142138493-79dcaf26-5036-4237-ae33-6c9e942252cd.png)
previous version 
![image](https://user-images.githubusercontent.com/6009737/142139112-9efbf6a8-fe86-47b1-b9fb-87431c17e2fe.png)


poison_immunity = {2}i change to poison_immunity = {2}독
For me, this is more clearly visible.

**Comment by soarqin** [comment]
sorry for my mistake, should be fixed in dccca18

**Comment by arithxp** [comment]
It works fine. thank you 👍
