### ISSUE TITLE
Players on map range

### ISSUE THREAD

**Issue by cakarlen** [soarqin/D2RMH#44]
I've noticed that you have to be fairly close to other players for them to show up on the minimap. Is there any way to mimic how the native minimap works in the sense that you can see other players far away?

**Comment by soarqin** [comment]
I have no idea to skip the anti-debugging mechanism of D2R, so it is hard to find how D2R store party players in memory

**Comment by cakarlen** [comment]
Hi! Could a project like [this](https://github.com/blacha/diablo2/tree/master/packages/memory) help with figuring this issue out?

**Comment by soarqin** [comment]
this is a memory scanner, it is not always working, while there may be malform info in memory after many games created

**Comment by soarqin** [comment]
implemented in 5c33550
