### ISSUE TITLE
Show immunities/enchantments/names for normal mobs

### ISSUE THREAD

**Issue by Sunblood** [soarqin/D2RMH#46]
Currently with all options enabled, immunities/enchantments/name labels are only shown for uniques/champions. I'd like to be able to see at least immunities for all mobs including normal.

**Comment by soarqin** [comment]
thinking of it for long, but text stacking makes the map layer horrible,

**Comment by soarqin** [comment]
just did a simple implementation, which cannot prevent text stacking at present

**Comment by soarqin** [comment]
released with v0.6.2, close.
