### ISSUE TITLE
Detected as trojan

### ISSUE THREAD

**Issue by Ostico** [soarqin/D2RMH#5]
The tool is detected as trojan by windows 10 defender:

`Trojan:Win32/Sabsik.FL.A!ml`

**Comment by soarqin** [comment]
if you trust my precompiled binary, just add the file to your anti-virus exclude list.
otherwise you can compile the codes yourself following the instruction.

**Comment by Ostico** [comment]
Hi @soarqin , my concern was to notify to you that some fingerprint in the executable is detected as trojan.

The workaround is pretty obvious, but i would suggest you to try to find a way to fix.

**Comment by soarqin** [comment]
hard to say what made it, but use hidden function in ntdll.dll is always a dangerous action, no way to avoid it while I wanna read memory from 64bit program from a 32-bit instance(which is required to load legacy d2 dlls).
