### ISSUE TITLE
CPU usage is high

### ISSUE THREAD

**Issue by PMySQLQ** [soarqin/D2RMH#52]
![image](https://user-images.githubusercontent.com/86890440/142403936-cd2792c8-2fc3-4317-b92b-66784579ba05.png)

**Comment by soarqin** [comment]
try set `fps` to a positive value (sugget 30 or 60) to see if the cpu usage is reduced, I have found that V-Sync on some video cards' drivers cosumes cpu usage a lot and dunno why
