### ISSUE TITLE
Add door indicators on map

### ISSUE THREAD

**Issue by cakarlen** [soarqin/D2RMH#55]

**Comment by cakarlen** [comment]
@soarqin I updated my exe and config file and don't see any door indicators. On latest commit also

**Comment by cakarlen** [comment]
Is there a specific way to update it? I recompiled and it didn't pull in a new copy

**Comment by jfcherng** [comment]
i assume it's just in `D2RMH\bin\D2RMH_data.ini`?

**Comment by soarqin** [comment]
sorry for forgot update it in bin. you can generate it by running `gendata "path to your D2R"`, note: put compiled gendata.exe and gendata.ini(in `bin` folder) in same folder

**Comment by soarqin** [comment]
pushed new D2RMH_data.ini
