### ISSUE TITLE
Map is stuck in center

### ISSUE THREAD

**Issue by CrazyPotatoes** [soarqin/D2RMH#59]
The options to have upper left or right corner don't work anymore. I tried playing with the centered on player and window limits options but the map is still stuck in the middle.

As a suggestion, what do you think about non-overlay mode? Separate window just for the map?

**Comment by soarqin** [comment]
please read comment about `map_area` entry in config carefully.
if you set `map_area` to 1.0,1.0, the map layer will be 100% width and height of the D2R window, so you will see the same layout for up-left/up-right/center `position` set.
set `map_area` to a smaller value when you set up-left/up-right in `position`

**Comment by PMySQLQ** [comment]
![image](https://user-images.githubusercontent.com/86890440/142733816-57fe1e5f-dc4f-4d5e-b9cd-47a3bcd6c799.png)
Do you want this effect

**Comment by PMySQLQ** [comment]
![image](https://user-images.githubusercontent.com/86890440/142733919-a4eadce7-d6e1-401e-9628-1549992bae02.png)

**Comment by PMySQLQ** [comment]
This effect is final

**Comment by PMySQLQ** [comment]
![image](https://user-images.githubusercontent.com/86890440/142734042-907249e3-c85f-43e6-a4e4-aaa94dc0baf3.png)

**Comment by soarqin** [comment]
@PMySQLQ Please don't talk about irrelevant topics in thread.
