### ISSUE TITLE
Feature Request Sound in loot filter

### ISSUE THREAD

**Issue by sunkwolf** [soarqin/D2RMH#60]
Would be nice to have 2 levels in the item drop filter, one whit out sound like for full juvs or white things and other whit sound for things like him rune + and shakos or tals rasha armor.

**Comment by soarqin** [comment]
I don't have time to find suitable sound files for default config.
so I won't add it recently, but pull requests are welcome.

**Comment by soarqin** [comment]
featured in v0.7
