### ISSUE TITLE
rare item message stuck on separate message list after selling to npc

### ISSUE THREAD

**Issue by GeminiCCCC** [soarqin/D2RMH#61]
after selling rare item (boot, circlet etc) to npc, item message will stuck on separate message list for ever.

**Comment by soarqin** [comment]
this seems like a bug

currently I use these 3 conditions to check if an item is on the ground:
1. the item is not belong to Player (onwerId == 0)
2. the item is not on body (position = 0)
3. the item is in somebody's inventory/cube/stash(invPtr != nullptr and itemPosition == 0 or 3 or 4)

so this item does not meet all of the three, but is in NPC's selling box
maybe there should some another field to indicate that the item is on the ground, I'd look the memory over later
