### ISSUE TITLE
调整地图位置

### ISSUE THREAD

**Issue by Asslio** [soarqin/D2RMH#63]
我如何在游戏中改变地图的显示位置？
例如：将小地图拖到右上角进行显示。
补充：我有尝试过调整position = 1，但我发现没有效果。
能否使用鼠标实现地图的位置拖动？

**Comment by soarqin** [comment]
https://github.com/soarqin/D2RMH/blob/master/contrib/D2RMH_CN.ini#L44-L45

鼠标是点不到地图层的所以没办法拖动，打算做自适应宽高的选项(0.6以前的做法)以解决这个设置困难的问题
