### ISSUE TITLE
Timer Only Increments by the Minute

### ISSUE THREAD

**Issue by derekShaheen** [soarqin/D2RMH#64]
Loving the new text / timer options on screen. However, it seems to only increment every minute, does not seem to show seconds as indicated (and hoped) in the config.

Thanks much for implementing this! Hoping I might just be doing something wrong.

![image](https://user-images.githubusercontent.com/38998433/143059090-6a018e59-aeb5-47f7-81f4-737877690fc6.png)
![image](https://user-images.githubusercontent.com/38998433/143059153-8da6a744-30e0-46b8-b379-8c4083057ca5.png)

Current text panel settings:

text_panel_pattern = {duration}{newline}{time}{newline}{difficulty}{newline}{act}-{mapname}
text_panel_position = 0.93,0.015,2

**Comment by soarqin** [comment]
fixed and updated binaries in v0.7 release, you can re-download it
