### ISSUE TITLE
Timer Resets Upon Area Change

### ISSUE THREAD

**Issue by derekShaheen** [soarqin/D2RMH#65]
Thanks for updating the timer! It does track the seconds correctly now. However, I'm seeing this does reset upon changing area, as opposed to leaving / entering a new game. Please see example video below.

https://user-images.githubusercontent.com/38998433/143082890-da256ac2-0a9c-4278-95c6-3703ad1f771e.mp4

**Comment by allangalera** [comment]
also the duration only starts when I open the map (my config is to show = 2 only when map is on)

btw awesome map <3
