### ISSUE TITLE
About performance.

### ISSUE THREAD

**Issue by zdl51go** [soarqin/D2RMH#67]
I play the game with 144HZ device. FPS in game has  maintained at 120.
D2RMH V0.5.4  just reduce FPS by 15. It's all right.
D2RMH V0.7 reduce FPS by 40.
It's a poor experience. 

Regards.

**Comment by soarqin** [comment]
you can try following ways to get it better:
1. try set `show_items=0`, `show_monsters=1` to see if it is better. performace impact is from semi-transparent layered window, so the more things displayed on map layer, the more fps losses
2. try set `fps` to -2, 60 or 30
3. try reduce D2R graphics quality

**Comment by zdl51go** [comment]
Thx, I'll try.
