### ISSUE TITLE
Windows Defender detects trojan

### ISSUE THREAD

**Issue by egdm42** [soarqin/D2RMH#69]
On 11/26 Windows Defender quarrantined D2RMH.exe v0.7 as Trojan:Win32/Sabsik.FL.A!ml

**Comment by HOURS1212** [comment]
see #5

**Comment by soarqin** [comment]
as of commit b92f068, binaries compiled with mingw32 will get fewest virus reports on virustotal.
so start of next version, D2RMH will be released in mingw32 compiled binaries, which is larger than MSVC compiled ones, but more friendly to anti-virus softwares
