### ISSUE TITLE
When starts, the executables suddenly shutdown.

### ISSUE THREAD

**Issue by Ostico** [soarqin/D2RMH#7]
No errors, it simply boot up and disappear.

There are some logs that i can read?

**Comment by soarqin** [comment]
did you follow the instruction in README(aka prepare a legacy d2 v1.13c)?

**Comment by Ostico** [comment]
I have a D2 + LOD installation on the same machine.

But i have version 1.14d ( actually it runs on battle.net ). 
Is the version 1.13c the only one which works?

**Comment by soarqin** [comment]
yeah, I think only 1.13a-1.13c is supported.
actually I can try to support v1.10 to v.12, but not for 1.14, coz not all required function addresses are revealed in 1.14.

**Comment by Ostico** [comment]
Thank you, got it!
