### ISSUE TITLE
language = zhCN 不生效

### ISSUE THREAD

**Issue by yjfyy** [soarqin/D2RMH#70]
language = zhCN 不生效了，只能language = zhTW?

**Comment by soarqin** [comment]
已经更新release里的zip，重新下载即可

**Comment by chang009400** [comment]
自己建構後 會產生
![1638096750135](https://user-images.githubusercontent.com/91673790/143764892-99b19055-d1fc-40c2-8957-65cb2f46a067.jpg)
~
