### ISSUE TITLE
自己嘗試建構

### ISSUE THREAD

**Issue by chen0707ww** [soarqin/D2RMH#71]
![1638096750135](https://user-images.githubusercontent.com/91673790/143765150-d1a4247d-f3c1-4a2f-9ae6-f22566349f57.jpg)

自己建構後  會變成旁邊都是白色條狀~~~

**Comment by soarqin** [comment]
構建環境能否詳細說明一下

**Comment by soarqin** [comment]
我知道是什麼問題了，已經在99c6342中修復

**Comment by chen0707ww** [comment]
謝謝哥~
