### ISSUE TITLE
misfunction of D2RMH with Multilauncher tool (D2RML by github sunblood)

### ISSUE THREAD

**Issue by AjaxAlfa** [soarqin/D2RMH#74]
Like your MH, big thanks.

I have two BN acc and play 2pp, today i tried MH with Multilauncher tool, seems not working.

what i did is open Multilauncher first , start D2R gaming window of both BN accounts (note: Multilauncher memorise token of BN accounts for hrs, so it skipped BN game platform logging with period), MH doesn't pop up while loading map of any window. normally MH pop up on first window but it doesn't.

Anyway, MH works without Multilauncher.

Thanks

**Comment by AjaxAlfa** [comment]
首先，感谢大佬，MH太棒了，让我这个路痴不再迷路。
我平时双开因为可以2PP，而且可以自己带自己。偶然看到双开工具也在GITHUB上，我试了下。好像用双开工具的开启方式不能让MH生效，即使图标在。

双开工具首先需要BN登录记住TOKEN，然后几个小时内都可以直接双开跳过BN平台，直接打开游戏。

当然，不开双开工具还是可以用MH的，第一个账号就能用。

感谢大佬的辛苦付出

**Comment by soarqin** [comment]
Please run as administrator from right-click menu

**Comment by soarqin** [comment]
otherwise you can try https://github.com/Farmith/D2RMIM which does not require admin rights

**Comment by AjaxAlfa** [comment]
Problem solved. i run as admin.
感谢大佬！
