### ISSUE TITLE
开了程序以后 GPU特别高

### ISSUE THREAD

**Issue by 198290208** [soarqin/D2RMH#75]
![微信截图_20211202211533](https://user-images.githubusercontent.com/44019941/144429467-e2d5286c-eaec-4bd5-b450-b3f2a9126915.png)
![微信截图_20211202211658](https://user-images.githubusercontent.com/44019941/144429480-c0021ec1-8b21-4a63-b7e8-ff7eff3765c0.png)

开了程序以后 GPU高 请问怎么处理？

**Comment by soarqin** [comment]
这个很正常，layered window本身就是用比较消耗gpu的方式来实现的，这是windows自己的机制，主要是半透明渲染比较耗

**Comment by soarqin** [comment]
目前推了一版新的半透明机制，可以从代码里编译后再测一下是否稍微降低了gpu需求

**Comment by 198290208** [comment]
> 现在推一版新的半透明机制，可以从代码里进一步判断一下是否可能降低gpu需求

新的透明机制很好。 GPU降低明显！
