### ISSUE TITLE
Feature Request - Auto Alt-F4

### ISSUE THREAD

**Issue by usafltg** [soarqin/D2RMH#76]
Not sure if possible, but would be very useful for HC players. Could be a variable setting that can be turned off or on, and allows alt-f4 command to be sent on PCs to auto close the active window if health drops below an adjustable pre-set percentage (i.e. if health < 98% of max, send alt-f4 command).

**Comment by jagarop** [comment]
i support that suggestion, and think a taskkill instead of alt f4 would be cleaner solution

; minimal hp percentage for chicken
chicken = 0.8

if (Hitpoints / Maxhp) >= chicken
taskkill d2r process

**Comment by soarqin** [comment]
it is a quite simple function.
but I just do think this might be a plug-in function for a map revealing tool, hard-code it with main functions are not good for maintainance.
I may desgin a plugin system while implementing this.

**Comment by soarqin** [comment]
implemented in f9f3a8d on branch `plugin_support`, you can try it if can compile it yourself
need more tweaks before final release

**Comment by jagarop** [comment]
> implemented in [f9f3a8d](https://github.com/soarqin/D2RMH/commit/f9f3a8d9bb417f54ca096d7c49bd1dccdb080e06) on branch `plugin_support`, you can try it if can compile it yourself need more tweaks before final release

managed to compile and run the new branch, but getting a error without debug message

https://i.imgur.com/j7QN0Oo.png

**Comment by soarqin** [comment]
you need to compile d2mapapi_piped

**Comment by jagarop** [comment]
> so it works as expected? note: you can edit `plugins\chicken_life.lua`, change 0.3 to your desired value

yes, its quitting game like intended :)

but if you just quit game it will close client as well. and if you join a new game with low hp (intown) it will close again.

i suggest checking for mapSeed != 0 (to check if its ingame, or any other idea you might have) to not quit in menus and do a inTown check as well (to not quit while inTown, since should be impossible to die there).

**Comment by soarqin** [comment]
yeah, that was tweaks what I have said.
more functions are being added soon to plugin system
