### ISSUE TITLE
Updated offsets following patch 1.167314

### ISSUE THREAD

**Issue by jack202121** [soarqin/D2RMH#78]

**Comment by soarqin** [comment]
please test if it works before firing an issue

**Comment by jack202121** [comment]
Update the new patch and the map is invalid

**Comment by soarqin** [comment]
> Update the new patch and the map is invalid

please confirm that you are running the latest version

**Comment by jack202121** [comment]
Yes, the latest version

**Comment by soarqin** [comment]
I have tested that it works fine, and no one else reports a failure here.
so please describe your problem clearly, better with reproduce steps or screenshots

**Comment by jack202121** [comment]
Working fine

**Comment by jack202121** [comment]
Sorry, it was my mistake
