### ISSUE TITLE
透明度没有用

### ISSUE THREAD

**Issue by PMySQLQ** [soarqin/D2RMH#82]
![image](https://user-images.githubusercontent.com/86890440/144837296-57497354-bf56-4906-8bb4-53d31f1903ee.png)
![image](https://user-images.githubusercontent.com/86890440/144837342-10d34fd7-bab4-4c7c-a89c-71436079bdc7.png)

**Comment by soarqin** [comment]
0.9里所有颜色增加了透明通道默认完全不透明，要完全透明后面再加一个0
