### ISSUE TITLE
ISBoxer/Innerspace Support

### ISSUE THREAD

**Issue by Jon310** [soarqin/D2RMH#83]
Hello, I was wondering if you would be open to adding support for games launched through ISBoxer/Innerspace? It is one of the easiest ways to launch multiple D2R instances and contains many window management advantages over the alternative multi launchers.

Thank you for what you do, this is an amazing tool!

 - Jon

**Comment by soarqin** [comment]
I have no idea about sandbox support, coz sandbox does what does it mean, software outside cannot touch anything inside it.
you had better ask certain softwares' tech support if they does support run auxiliary tools with games in the same sandbox space.

**Comment by Jon310** [comment]
Thank you for the response, I appreciate all you do.

**Comment by mengerpiao** [comment]
可惜了。不能脱离于BNet之外运行。
