### ISSUE TITLE
Feature request: Show lobby name in text area

### ISSUE THREAD

**Issue by derekShaheen** [soarqin/D2RMH#84]
Would like to request the ability to show the lobby name in the custom text area. I often forget what baal run # I'm on, and need to tab the normal map to check it. Small but appreciated convenience.

**Comment by VanLime** [comment]
I'd like to add to this, display game IP in custom text area

**Comment by soarqin** [comment]
Currently I don't know how to get lobby name from memory, need some research.
game IP is found, will be added later

**Comment by derekShaheen** [comment]
Would also like to request the ability to add 'area level' to the text box

**Comment by soarqin** [comment]
implemented in dd439eb
