### ISSUE TITLE
FPS reduce

### ISSUE THREAD

**Issue by zdl51go** [soarqin/D2RMH#90]
I've tried every option in setting,  D2RMH always reduce about 30fps.
The other tool : https://github.com/OneXDeveloper/MapAssist  doesn't have this problem. 
May be the rendering of overlay is different ? 
But I prefer D2RMH more.
Hope the performance will improve :) 

Regards.

**Comment by soarqin** [comment]
it should be better since v0.9.0, but using OpenGL is still costs GPU a little

**Comment by zdl51go** [comment]
It much better than before.
The feeling of frame lost is gone though there is a 10-15 fps reduction。
