### ISSUE TITLE
Dose any possible will resolve the conflict with gsync? 

### ISSUE THREAD

**Issue by sss1243a789** [soarqin/D2RMH#93]
没人遇到此问题吗, gsync compatible在启用地图后停止运作,显示器刷新率被固定在最高不再变动..

**Comment by soarqin** [comment]
将fps设为正数(25或者30)试试

**Comment by sss1243a789** [comment]
> 将fps设为正数(25或者30)试试

各种帧率试过了不行...打开地图显示器刷新率就固定了.可能是我显示器gsync功能有些问题,开的全屏,开窗口帧数会跳到但实际根本就不管用反而更卡

**Comment by soarqin** [comment]
D2R的显示选项里打开垂直同步试试，D2的逻辑只有25帧，不开垂直同步也没意义
